architecture/arborescence, Router, Header
Blodispic/transcendance pull request #6
Opened 2023-01-11 14:41 UTC by emmanuel-lbs

1. Refonte de l'arborescence du front avec le dossier components qui possède toutes les pages web et autres components notamment le jeu qui est passer de **App.tsx** à **Component/Game/Game.tsx**

2. Création du router qui permet la redirection vers d'autre page et avec les liens qui redirige bien vers d'autre page déjà crée.
**Le concept de monopage est validé**

3. Avec ceci, le Header a pu voir le jour présent sur toutes les pages,  
il est pas très beau mais nique

2023-01-11 15:26 UTC, Blodispic requested changes
- [ ] Je pense qu'on devrait changer les href par des Link to, pas besoin de faire un href vu qu'on se balade sur la même instance.

- [ ] On peut rechanger game par root dans index.tsx vu que router ne concerne pas que le jeu

- [ ]  On peut retirer les link sur bootstrap dans index.html a la demande de l'empereur manu

2023-01-11 15:26 UTC, Blodispic commented on front/public/index.html
> +<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="an
C'est quoi ?

2023-01-11 15:26 UTC, Blodispic commented on front/src/components/Header/Header.tsx
> +        <a href="/Game"> Game </a>
Link to="/Home">

2023-01-11 15:26 UTC, Blodispic commented on front/src/index.tsx
> +const game = ReactDOM.createRoot(
On peut surement le renommer a root du coup, vu qu'on appelle router qui est la base de tout le site

2023-01-12 13:22 UTC, Blodispic approved these changes

2023-01-12 13:38 UTC, KobeLaC approved these changes

2023-01-13 09:07 UTC, se-lee reviewed
jaime

2023-01-13 09:08 UTC, se-lee approved these changes

2023-01-13 12:00 UTC, merged